blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
    path('create/', PostCreateView.as_view(), name='create'),
]

generic_views/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):

    title = models.CharField(max_length=100)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.id})
    

    class Meta:
        ordering = (
            '-created_at', 
            '-modified_at',
        )

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:

        model = Post
        fields = [
            'title',
            'content',
        ]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse
from .models import Post
from .forms import PostForm

class PostListView(ListView):

    template_name = 'blog/list.html'
    queryset = Post.objects.all()
    context_object_name = 'blogs'

class PostDetailView(DetailView):

    template_name = 'blog/detail.html'
    context_object_name = 'blog'

    def get_queryset(self):
        # self.kwargs['pk] or self.kwargs.get('pk)
        return Post.objects.filter(id=self.kwargs.get('pk')) 
    
class PostCreateView(CreateView):

    template_name = 'blog/create.html'
    form_class = PostForm
    success_url = '/'

class PostUpdateView(UpdateView):

    template_name = 'blog/update.html'
    form_class = PostForm
    success_url = '/'

    def get_queryset(self):
        # self.kwargs['pk] or self.kwargs.get('pk)
        return Post.objects.filter(id=self.kwargs.get('pk')) 

class PostDeleteView(DeleteView):

    template_name = 'blog/delete.html'
    success_url = '/'
    context_object_name = 'blog'

    def get_queryset(self):
        # self.kwargs['pk] or self.kwargs.get('pk)
        return Post.objects.filter(id=self.kwargs.get('pk')) 

blog/templates/blog/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create View
{% endblock title %}
    

{% block header %}
    Create View
{% endblock header %}
    


{% block content %}

<div class="container">
    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Goto Back</a>
    <div class="m-2">
        <div class="card">

            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-info" type="submit">Create Post</button>
            </form>

        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/delete.html
{% extends 'base.html' %}


{% block title %}
    Delete View
{% endblock title %}
    


{% block header %}
    Delete View
{% endblock header %}
    
{% block content %}
<div class="container">
    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Goto Back</a>
    <div class="m-2">
        <div class="card">
            <div class="p-5">
                Do you really want to delete blog post with title : {{blog.title}} ?
                <form method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger mt-3" type="submit">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/detail.html
{% extends 'base.html' %}


{% block title %}
    Detail View
{% endblock title %}
    



{% block header %}
    Detail View
{% endblock header %}
    
{% block content %}
<div class="container">
    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Goto Back</a>
    <div class="m-2">
        <div class="card">
            <div class="card-header">
                <p class="card-title">
                    <span class="font-weight-bold">
                        {{blog.title}}
                    </span>
                    at {{blog.created_at}}
                </p>
            </div>
            <div class="card-body">
                <p class="card-text">
                    {{blog.content}}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/list.html
{% extends 'base.html' %}


{% block title %}
List View
{% endblock title %}


{% block header %}
    List View
{% endblock header %}
    



{% block content %}

<div class="container">
    <a href="{% url 'blog:create' %}" class="btn btn-secondary">Create Post</a>
    {% for blog in blogs %}
    <div class="m-2">
        <div class="card">
            <div class="card-header">
                <p class="card-title">
                    <span class="font-weight-bold">
                        {{blog.title}}
                    </span>
                    at {{blog.created_at}}
                </p>
            </div>
            <div class="card-body">
                <p class="card-text">
                    {{blog.content}}
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-outline-info" href="{{blog.get_absolute_url}}">Detail View</a>
                <a class="btn btn-outline-info" href="{% url 'blog:update' blog.id %}">Update View</a>
                <a class="btn btn-outline-danger" href="{% url 'blog:delete' blog.id %}">Delete View</a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock content %}

blog/templates/blog/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update View
{% endblock title %}
    

{% block header %}
    Update View
{% endblock header %}
    
{% block content %}

<div class="container">
    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Goto Back</a>
    <div class="m-2">
        <div class="card">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-info" type="submit">Update Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>
        {% block title %}
        Base Page
        {% endblock title %}
    </title>
</head>

<body> <div class="jumbotron bg-info">
    <p class="h3 text-center text-light">
        {% block header %}
            All Blogs
        {% endblock header %}
    </p>
</div>
    {% block content %}

    {% endblock content %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>